### ISSUE TITLE
3.11.1 - outstanding pieces

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1747]
- [x] #481 - Edit box is not updated at all (as in 'Browse Data') when in 'Execute SQL'
- [x] #1045 - DB Browser Crashes When Importing Its Own .sql dump
- [x] #1161 - Updated query optimisations
- [x] #1595 - Network inaccessible error when using a WiFi network
- [x] #1654 - "determining row count" displays forever in Browse Data tab
- [x] #1660 - About Info - display 32bit vs 64bit
- [x] #1670 - Allow bottom editor of Execute SQL tab to grow taller
- [x] #1731 - TEXT values show as BLOB 
- [x] #1732 - Error encrypting in 3.11.0
- [x] #1733 - It's not possible to modify some tables
- [x] #1740 - Class 'NullLineEdit' lacks Q_OBJECT macro
- [x] - Include SQLite 3.27.1 instead of SQLite 3.26.0
- [ ] ~#1493 - Night Mode or Dark Theme~
  * Unlikely to be solved any time soon, as dark mode support seems to still be "in progress" for Qt itself.  We can't complete this for all supported OS's until Qt itself reasonably supports them.  eg:
    * Windows ([Qt bug here](https://bugreports.qt.io/browse/QTBUG-72028))
    * macOS ([QtLabel wrong colour](https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-464075616))
  * We'll just note Dark Mode theme support is known to be broken on Windows and macOS.

Building new release binaries right now. :smile:

**Comment by mgrojo** [comment]
> Should we just release 3.11.1 "as is" and update the Release Notes to say we don't yet support Dark Mode at all?

In Linux, it works like a charm :wink: but yes I agree with releasing as is and publicize that it is not yet supported in Windows and Mac.

 I think there are other bug fixes that we could consider for including in v3.11.1 if they are simple enough, for example, after making a quick review: 
7e549c7c4ccb387ac8acb8cea3c11423e8bcaa93
1925ccfd37bea327683a6704de625e47dc260cf4
0ffed5e287f6b006db0c271f1ba406ca915ac584
79ffd779b92a1e2093ad6ce7052b33d8d152141d
58f52f13cb6700e4503f667c9e49718f653906de

**Comment by justinclift** [comment]
> I think there are other bug fixes that we could consider ...

Yeah, they all look pretty simple, and unlike to introduce breakage.  It's fine to commit those (and any other simple looking stuff you want) to the `3.11.x` branch. :smile:

**Comment by justinclift** [comment]
> In Linux, it works like a charm :wink: but yes I agree on releasing as is and publicize that it is not yet supported in Windows and Mac.

Been thinking over this today.  Yeah, I think that'll be the way to go. :smile:

**Comment by mgrojo** [comment]
> Yeah, they all look pretty simple, and unlikely to break anything. It's fine to commit those (and any other simple looking stuff you want) to the `3.11.x` branch. :smile:

Am I still on time for adding those commits?

**Comment by justinclift** [comment]
Yeah, go for it.  Still doing builds to test #1595 at the moment.  Might not have everything wrapped up for another day anyway. :man_shrugging:

**Comment by mgrojo** [comment]
I've cherry-picked only three of the commits. The remaining ones, although simple, raise conflicts, so it would require time to fix and check. For the moment, I leave it as is.

**Comment by justinclift** [comment]
Thanks heaps @mgrojo, sounds good. :smile:

**Comment by justinclift** [comment]
@MKleusberg Windows 3.11.1 binaries are ready for signing:

* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.11.1-win32.msi
  * SHA256: 9adfece6d45397031877cc02252a3caf2b09c1524787d262b0e7371e259ad82d
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.11.1-win32.zip
  * SHA256: 41d2a1ec3d7327827ff827ece0a9ca4ee11225b8c0bb81a44b0b456d3c33350f
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.11.1-win64.msi
  * SHA256: a7be5182c7a504926cfeded339e580917950af0465efc730001dc0fa9fce5d30
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.11.1-win64.zip
  * SHA256: 92ddd5069222bb531bb378e8fe608701978627aa0ae9e9d7aa3127b2d6cc5caf

When that's done, there's a new (Draft status) 3.11.1 Release ready to receive them.  The SHA256 checksums at the bottom will need updating for the new signed version of the files.

Am building the macOS ones shortly.  If they're already attached to the new release when you attach yours, that means it's 100% ready so you're good to hit the Publish button. :smile:

**Comment by justinclift** [comment]
macOS build:

* https://nightlies.sqlitebrowser.org/osx-prerelease/DB.Browser.for.SQLite-3.11.1.dmg
  * SHA256: bd4a74540a63a262fc49b816e8fc71fd816e81b215c31572d96b169d980a573e

It was built on macOS Mojave using Qt 5.11.3.  Haven't yet done any sanity tests on it, but will shortly.

**Comment by MKleusberg** [comment]
Aaand it's published :smile: I have already updated the README file and the issue templates in the master branch. The binaries still need to be uploaded to our Website plus updating of the website itself. When that's done, the currentrelease file can be updated.

**Comment by justinclift** [comment]
Excellent.  I'm about to get some sleep, so will get all this stuff done after that. :smile:

**Comment by justinclift** [comment]
The download cluster and main website have been updated for 3.11.1.  Now it's sleep time. :wink:

**Comment by justinclift** [comment]
Its been 24 hours, and no major show-stopper type bugs have been reported yet.

I'll update the currentrelease file soon, so the update prompt starts happening for people. :smile:
