### ISSUE TITLE
3.11.2 - outstanding pieces

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1773]
* [x] #1756 - Enable 'Edit Database Cell' when view is editable
* [x] #1758 - DB browser crashes when I try to attach additional database to current one    
* [x] #1764 - CASE-SENSITIVITY: Error importing data from SQL file: cannot start a transaction within a transaction
* [x] #1772 - Cell edit window considers binary data to be text/numeric if first byte is in ascii range
* [x] #1774 - Crashes when browsing a empty view with view editing enabled
* [x] #1777 - Trying to save after successfull import fails
* [x] #1799 - Attach encrypted database results in Out of Memory Error
* [x] #1814 - File is not a database
* [x] #1829 - Can't remove password from an encrypted database any more
* [x] 1a59c8cbda47684dfc0b55283fc6fdb396adc832 - grammar: Fix keywords as table name and keywords as column name 
* [x] Include SQLite 3.27.2 instead of SQLite 3.27.1
* [x] Include [SQLCipher 4.1.0](https://discuss.zetetic.net/t/sqlcipher-4-1-0-release/3490) instead of 4.0.1
* [x] Updated translation strings
  * #1600 - Korean
  * #1830 - Brazilian Portuguese
  * #1833 - Italian
  * e2ad5459d569801f9a635391f774e81ca1009e85 - German

**Comment by MKleusberg** [comment]
I consider #1733 (and related to it e52f2054f2aa1d0bbee8dbeac635e74963022f94) to be a serious problem too. ... which reminds me to cherry-pick e52f2054f2aa1d0bbee8dbeac635e74963022f94 to the 3.11.x branch :wink:

**Comment by justinclift** [comment]
Thanks, just added those. :smile:

**Comment by justinclift** [comment]
Hang on... #1733 looks like it was merged in time for 3.11.1.

**Comment by MKleusberg** [comment]
Oh you're right! :smile: But there's still e52f2054f2aa1d0bbee8dbeac635e74963022f94 which breaks the grammar parser in similar ways.

**Comment by justinclift** [comment]
Yeah, that's why I added 1a59c8cbda47684dfc0b55283fc6fdb396adc832.  That's the `3.11.x` version of that commit yeah?

**Comment by MKleusberg** [comment]
Yep, it is :smile:

**Comment by justinclift** [comment]
Thanks. :smile:

**Comment by mgrojo** [comment]
#1772 should be fixed in 0adb0af13342f5a12cbfae43ae2b5a176b6a21ea and I think it could be brought to the release branch.

@MKleusberg maybe you could take a look to the solution, just in case you come up with a better approach or still pending gaps. I was surprised by the fact that [`QString QTextCodec::toUnicode(const char * input, int size, ConverterState * state = 0) const`](https://doc.qt.io/archives/qt-4.8/qtextcodec.html#toUnicode-2) ends at the first zero in `input` instead of continuing up to `size`. Do you think it could be a bug in Qt?

**Comment by mgrojo** [comment]
> @mgrojo The QDarkStyle fix looks like it might work ok... not sure if the code is suitable for our stable/release branch or not though?

It might be ready for release, but it contains a lot of changes. Maybe the cherry-picking raises conflicts.

**Comment by justinclift** [comment]
> Maybe the cherry-picking raises conflicts.

Yeah, I haven't checked yet.  Was more thinking that even if it doesn't raise conflicts... not sure that we've really had many people testing it yet.  Kind of nervous to put it in, this far along the stabilising of a major release...

... on the other hand, a lot of people do seem to want a dark theme available.

Thoughts? :smile:

**Comment by MKleusberg** [comment]
@mgrojo I think your commits looks reasonable. I have no better idea either :smile: But I don't think it's a bug in Qt. In the docs they say
> Converts the first size characters from the input from the encoding of this codec to Unicode

which to me sounds like the size parameter doesn't determine the length of the input but only how much of the input should be converted. So while I think what we want would make more sense, this doesn't sound like a bug in Qt.

**Comment by mgrojo** [comment]
@MKleusberg I guess they'd claim is working as expecte, but it is a bit inconsistent, because some codecs will stop at the first zero and others not, because that is a valid encoding pattern, like in UTF-16. In fact, I've checked that the same behaviour is in the ISO-8859-1 and I guess in all of the ISO-8859 encodings. 
```cpp
    if((encoding.isEmpty() || encoding.startsWith("ISO-8859")) && data.contains('\0'))
       return false;
```
Probably a lot more encodings don't use embedded zeros, but I think we can leave it as above, unless someone comes up with a better idea.

**Comment by justinclift** [comment]
It looks like https://github.com/sqlitebrowser/sqlitebrowser/issues/1772#issuecomment-469036623 still has some fine tuning to do.

I'll move the release date for 3.11.2 back a week, so there's some breathing space to investigate, etc.

I'm not personally ready to make the release yet anyway, as I'm focusing on getting a first working version of [`dio`](https://github.com/sqlitebrowser/dio/tree/dbhub_v2) released.  In the final stretch for that (maybe today or tomorrow?) so ignoring most of everything until then. :smile:

**Comment by justinclift** [comment]
@MKleusberg The patch for #1758 isn't in the `v3.11.x` branch yet.  Want to cherry-pick it across? I can do it if you can't be bothered. :smile:

**Comment by MKleusberg** [comment]
@justinclift No worries, I have just cherry-picked it :smile: Thanks for pointing this one out by the way!

@mgrojo I completely agree with everything you said :smile: At some point it probably makes sense to change the entire binary detection code anyway, so for now this is hopefully good enough.

**Comment by justinclift** [comment]
In theory, we should be releasing 3.11.2 tomorrow or so.

* How do people feel about it's current state?
* Are there other issues/PRs/etc that should be included?

I'm not sure on the status for #1772.  It kind of sounds like the patch there introduced incorrect character counts, and I'm not sure what's going on with that. :wink:

**Comment by mgrojo** [comment]
> I'm not sure on the status for #1772. It kind of sounds like the patch there introduced incorrect character counts, and I'm not sure what's going on with that.

The incorrect character counts (in fact, stripping of CR characters), predates #1772 and it's even present in v3.11.x. The solution (#1793) is too disruptive to be added, because it involves replacing the Qt widget by the QScintilla one.

I've added the two commits fixing #1772 to the v3.11.x branch.

**Comment by justinclift** [comment]
Thanks @mgrojo.  Sounds like we've done the best we can with that for the `v3.11.x` branch then, so that'll have to do. :smile:

I'll build our macOS & Windows release binaries for 3.11.2 today or tonight, so we're good to release when @MKleusberg has time to sign the Windows bits. :smile:

My focus stuff (the dio command line utility) is taking a **lot** longer than I was hoping for.  The first pass of it was finished last night, but it **really** needs unit tests added to catch at least the straight forward bugs.  And there will be bugs. :wink:

**Comment by MKleusberg** [comment]
@justinclift Did you have the time to build the binaries yet? I could easily sign them this week. But any later day would work too :smile:

**Comment by justinclift** [comment]
> Did you have the time to build the binaries yet?

Not yet.  Super focused on getting the the unit tests for dio finished (should be done tonight) so it's releasable.  There are ~30 pieces of dio to write tests for, and I'm on the last one now (as of last night).

I'm thinking the binary building will probably be friday. :smile:

**Comment by justinclift** [comment]
Binary building is going to be tomorrow instead of today.  I've just now finished the `dio` bits I wanted to get done, but I'm pretty sleepy and that's not the right time to be building a software release. :wink:

**Comment by justinclift** [comment]
It sounds like we still have problems with attaching databases (#1799), so one of the main issues for 3.11.2 (#1758) isn't completely fixed yet. :scream:

**Comment by beRto-** [comment]
@justinclift - @mgrojo completed a fix for #1709 on Feb 23. Can you please advise if that is getting picked up on the 3.11.2 release? I don't see it in the list above.

**Comment by justinclift** [comment]
I've no objections to including it, if @mgrojo feels it's a decent idea. :smile:

**Comment by mgrojo** [comment]
I've just reapplied the changes for #1709 to the v3.11.x branch. This will require a translation of two new strings (since the former translation string has been splitted):


 ```xml
   <message>
        <location filename="../MainWindow.cpp" line="1476"/>
        <location filename="../MainWindow.cpp" line="1478"/>
        <source>At line %1:</source>
        <translation>En la línea %1:</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="1476"/>
        <location filename="../MainWindow.cpp" line="1478"/>
        <source>Result: %2</source>
        <translation>Resultado: %2</translation>
    </message>

```

And this is the vanished string:
```xml
    <message>
        <source>-- At line %1:
%4
-- Result: %3</source>
        <translation type="vanished">-- En la línea %1:
%4
-- Resultado: %3</translation>
    </message>

```
This was added previously to the branch and it isn't translated yet:

```xml
    <message>
        <location filename="../AboutDialog.cpp" line="22"/>
        <source>Built for </source>
        <translation>Compilado para</translation>
    </message>
```

**Comment by justinclift** [comment]
k, lets ping the various translators and see if anyone responds in time.  I need to grab sleep soon anyway, so the new release won't be built in the next few hours. :smile:

**Comment by justinclift** [comment]
As a thought, since likely fixes for #1814, #1799, and #1777 were committed to `master` yesterday... lets wait a few days (Friday?) to see they're still looking good in a few days time.  If they are, then I think we're good to do the 3.11.2 release. :smile:

**Comment by justinclift** [comment]
Just created a stub draft 3.11.2 release, and am creating release binaries atm.

**Comment by justinclift** [comment]
Compiling with SQLCipher 4.1.0 (released a few weeks ago) seems to work ok.

I haven't yet checked if the fixes for #1814/#1799/#1777 will apply cleanly to the `v3.11.x` branch.  Will do so shortly.

**Comment by MKleusberg** [comment]
@justinclift I can cherry-pick them and fix and conflicts if you want to.

**Comment by justinclift** [comment]
@MKleusberg Excellent!

But take a look at #1829 (just created it) first.  I suspect that'll be a simple thing to fix. :smile:

**Comment by MKleusberg** [comment]
Sure I'll take a look :smile: By the way, because #1777 depends on #1764 I have cherry-picked the commits for the latter one too. I haven't yet added it to the release notes though.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by mgrojo** [comment]
@SafaAlfulaij @FriedrichFroebel @mvt91 @Feyn-Man @GortiZ6 @progh2 @bartlomiej-przymus  @bernardosulzbach @schdub @bssthu We'd like to let you know that there is a new fix release of DB4S with three new strings to be translated (see details in https://github.com/sqlitebrowser/sqlitebrowser/issues/1773#issuecomment-476345115). Would you have some time to update the translations? It is also a good opportunity to add some progress to the not yet complete translations.

**Comment by justinclift** [comment]
Thanks @mgrojo, I completely forgot. :smile:

**Comment by justinclift** [comment]
k, lets see how things stand on mon/tue and decide whether to rebuild then, etc.

**Comment by FriedrichFroebel** [comment]
As I am currently too lazy to set everything up for those six strings, I am going to add their German translations here.

```xml
    <message>
        <location filename="../AboutDialog.cpp" line="22"/>
        <source>Built for </source>
        <translation>Erstellt für </translation>
    </message>
    <message>
        <location filename="../sqlitedb.cpp" line="1085"/>
        <source>didn&apos;t receive any output from %1</source>
        <translation>%1 hat nichts ausgegeben</translation>
    </message>
    <message>
        <location filename="../sqlitedb.cpp" line="1091"/>
        <source>could not execute command: %1</source>
        <translation>Befehl konnte nicht ausgeführt werden: %1</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="1476"/>
        <location filename="../MainWindow.cpp" line="1478"/>
        <source>At line %1:</source>
        <translation>In Zeile %1:</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="1476"/>
        <location filename="../MainWindow.cpp" line="1478"/>
        <source>Result: %2</source>
        <translation>Ergebnis: %2</translation>
    </message>
    <message>
        <location filename="../SqlExecutionArea.ui" line="217"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Results of the last executed statements.&lt;/p&gt;&lt;p&gt;You may want to collapse this panel and use the &lt;span style=&quot; font-style:italic;&quot;&gt;SQL Log&lt;/span&gt; dock with &lt;span style=&quot; font-style:italic;&quot;&gt;User&lt;/span&gt; selection instead.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Ergebnisse der zuletzt ausgeführten Statements..&lt;/p&gt;&lt;p&gt;Alternativ kann dieses Panel zusammengeklappt und stattdessen der &lt;span style=&quot; font-style:italic;&quot;&gt;SQL-Log&lt;/span&gt;-Dock mit der Auswahl &lt;span style=&quot; font-style:italic;&quot;&gt;Benutzer&lt;/span&gt; verwendet werden.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
```

**Comment by justinclift** [comment]
Thanks @FriedrichFroebel, added in e2ad5459d569801f9a635391f774e81ca1009e85. :smile:

**Comment by GortiZ6** [comment]
Updated the italian translation, I've made a pull request #1833

**Comment by justinclift** [comment]
@GortiZ6 Thanks. :smile:

I may have mucked that up slightly.  I applied the new translations to our main development branch (eg, what will go into 3.12.0), instead of applying it to our release branch (for the upcoming 3.11.2 release).  Did I get that wrong?

**Comment by justinclift** [comment]
Just in case it helps, I've regenerated the .ts files in the v3.11.x branch.  It still has the "unfinished" strings, so should I apply your PR to this as well?

&nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/v3.11.x/src/translations/sqlb_it.ts

**Comment by GortiZ6** [comment]
Ouch! You're right, I've done the changes from the "master" branch. I haven't checked the v3.11x branch, anyway if the strings are a subset of master, you can pick them from there :) Thanks.

**Comment by justinclift** [comment]
Thanks @GortiZ6. :smile:

I'll get that done later one today, before creating the new 3.11.2 release builds. :smile:

**Comment by justinclift** [comment]
Done in d389a627c0704db0722b6e3509d9cb5dddee1e8c. :smile:

**Comment by justinclift** [comment]
Started getting this done, but need sleep.  Will pick this up in the morning instead.

**Comment by justinclift** [comment]
@MKleusberg The Windows binaries are ready for signing + adding to the draft 3.11.2 release. :smile:

* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.11.2-win32.msi
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.11.2-win32.zip
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.11.2-win64.msi
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.11.2-win64.zip

**Comment by MKleusberg** [comment]
Ok, give me a minute :smiley:

**Comment by MKleusberg** [comment]
And it's done :smile: They are all signed and added to the release draft.

**Comment by justinclift** [comment]
Excellent, thanks.  I'm still updating bits on the mac build server... it's nearly done. :smile:

**Comment by MKleusberg** [comment]
Awesome :smile: So we might get a new release today if things go well :champagne:

**Comment by justinclift** [comment]
Yep, just published it:  https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.2  :man_dancing: :champagne: :balloon: :tada: 

I'll get the README + website updated (etc) over the next few hours. :smile:

**Comment by justinclift** [comment]
Now unpublished.  Guess who forgot to update the version info in the release field... yep me.  Dammit.

Ok, getting that done now.  **\*sigh\***

**Comment by justinclift** [comment]
@MKleusberg Fixed windows builds:

* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.11.2-win32.msi
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.11.2-win32.zip
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.11.2-win64.msi
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.11.2-win64.zip

**Comment by justinclift** [comment]
Just added the (fixed) macOS .dmg to the draft release.  Feel free to hit the publish button when the new windows binaries are signed (etc). :smile:

**Comment by mvt91** [comment]
Hi Manuel,

I'll have a look this week if possible.

best regards
Michel
----- Mail d'origine -----
De: Manuel <notifications@github.com>
À: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: mvt91 <mvt91@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Sat, 30 Mar 2019 12:37:21 +0100 (CET)
Objet: Re: [sqlitebrowser/sqlitebrowser] 3.11.2 - outstanding pieces (#1773)

@SafaAlfulaij @FriedrichFroebel @mvt91 @Feyn-Man @GortiZ6 @progh2 @bartlomiej-przymus  @bernardosulzbach @schdub @bssthu We'd like to let you know that there is a new fix release of DB4S with three new strings to be translated (see details in https://github.com/sqlitebrowser/sqlitebrowser/issues/1773#issuecomment-476345115). Would you have some time to update the translations? It is also a good opportunity to add some progress to the not yet complete translations.

**Comment by justinclift** [comment]
@mvt91 Ahhh, we've already created the release binaries, so maybe next time instead? :wink:

**Comment by MKleusberg** [comment]
Heh heh, no problem! I have just signed the new binaries and will publish the updated release in a second.

**Comment by justinclift** [comment]
Thanks.  I'll get the rest of the bits done (eg download cluster, website post, etc). :smile:

**Comment by justinclift** [comment]
@deepsidhu1313 @lbartoletti We've just released DB4S 3.11.2, if you're interested in updating your packaging bits. :smile:

&nbsp; &nbsp; https://sqlitebrowser.org/blog/version-3-11-2-released/

**Comment by justinclift** [comment]
Hmmm, just realised we should be including an AppImage with this release.

Um... @deepsidhu1313, any interest in building it and adding it directly to the 3.11.2 GitHub Release?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.2

**Comment by deepsidhu1313** [comment]
Yeah sure.

**Comment by justinclift** [comment]
Thanks @deepsidhu1313.  When you've added it to the release info, please let me know.  I'll then copy it to our download cluster for that to be the main download source for it, so we can count downloads ourselves instead of having to rely on stats from GitHub. :smile:

**Comment by justinclift** [comment]
I think everything I needed to do for the release is done now, and all of the appropriate people notified.  Time to get some sleep. :smile:

**Comment by mvt91** [comment]
Hi Justin,

No problems.
I found the nightly test data. I'll can check next time some functionalities I don't know about :)

Time is going to much quickly for me. New decade this month :)

Best regards

Michel

----- Mail d'origine -----
De: Justin Clift <notifications@github.com>
À: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: mvt91 <mvt91@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Wed, 03 Apr 2019 17:47:04 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] 3.11.2 - outstanding pieces (#1773)

@mvt91 Ahhh, we've already created the release binaries, so maybe next time instead? :wink:

**Comment by deepsidhu1313** [comment]
Sorry guys, just busy with Job project. Sending product for client review.
Will look into releasing packages today. Apologies for the delay.

**Comment by justinclift** [comment]
No worries @deepsidhu1313, Real Life takes priority. :smile:

**Comment by justinclift** [comment]
Closing this issue, as 3.11.2 is out and nothing seems to have broken (badly).  We can keep updating this with info if needed, and/or open new issues where appropriate. :smile:
